language: julia
os:
    - linux
julia:
    - 0.4
    - nightly
env:
  global:
    - PYCALL_DEBUG_BUILD="yes"
  matrix:
    - PYTHON="python2.6" # not actually supported, here to test Conda
    - PYTHON="python2.7"
    - PYTHON="python3.1"
    - PYTHON="python3.2"
    - PYTHON="python3.3"
    - PYTHON="python3"
before_install:
    - sudo apt-add-repository ppa:fkrull/deadsnakes
    - sudo apt-get -qq update
    - sudo apt-get install -y $PYTHON
notifications:
    email: false
