language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - nightly
python:
    - 2.6 # Not actually supported, just for testing Conda
    - 2.7
    - 3.4
    - 3.5
env:
  global:
    - PYCALL_DEBUG_BUILD="yes"
notifications:
    email: false
